package parallel;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/AAAA_MyTest1_scenario002_run001_IT.feature"},
    plugin = {"json:target/cucumber-report/AAAA_MyTest1_scenario002_run001_IT.json","html:target/cucumber-report/AAAA_MyTest1_scenario002_run001_IT"},
    glue = {"glue"}
)
public class AAAA_MyTest1_scenario002_run001_IT extends AbstractTestNGCucumberTests{
}
// Generated by Cucable

