package parallel;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/MyTest2_scenario001_run001_IT.feature"},
    plugin = {"json:target/cucumber-report/MyTest2_scenario001_run001_IT.json","html:target/cucumber-report/MyTest2_scenario001_run001_IT"},
    glue = {"glue"}
)
public class MyTest2_scenario001_run001_IT extends AbstractTestNGCucumberTests{
}
// Generated by Cucable

